import type { WorkloadClass } from '@polyrouter/shared';

/**
 * Bundled per-class WORKLOAD anchor exemplars (add-semantic-workloads D4). The
 * offline spike at Plans/Workload.md ("Pre-flight spike", corpus in
 * Plans/w3-spike/) seeded this set: 5 classes × 30 curated prompts, serialized
 * through the SAME extractor as live requests, embedded once at boot, and
 * averaged into one unit-norm centroid per class. The classifier computes the
 * argmax over ALL FIVE but EMITS only the reserved classes (research / writing)
 * — the structural classes' anchors exist so a reserved class is claimed only
 * when it also beats them.
 *
 * VERSIONED: `WORKLOAD_ANCHOR_SET_ID` and the canonical content hash are part
 * of the semantic workload revision; any edit here is a new revision and MUST
 * bump the set id (a test pins the hash).
 */
export const WORKLOAD_ANCHOR_SET_ID = 'workload-v1';

/** sha256 over JSON.stringify of { class (sorted): anchors (sorted) } — pinned. */
export const WORKLOAD_ANCHOR_CONTENT_HASH =
  '7660c91e6a0bde4786b93b08b6f8f4c34c55fad5b5bf022bee0e2e421bdadfcb';

export const WORKLOAD_ANCHORS: Readonly<Record<WorkloadClass, readonly string[]>> = {
  code: [
    'Write a Python function that parses an ISO-8601 timestamp and returns a timezone-aware datetime.',
    'Why does my React component re-render on every keystroke even though the props did not change?',
    'Convert this SQL query with three JOINs into an equivalent Django ORM expression.',
    'Fix the off-by-one error in my loop that iterates over the last element twice.',
    'Explain what this regular expression matches and rewrite it to be readable.',
    'Refactor this 300-line function into smaller pure functions without changing behavior.',
    'Add unit tests for the retry helper, covering timeouts and the maximum-attempts case.',
    'What does git rebase --onto do, and when would I use it instead of merge?',
    'Implement binary search over a sorted array of integers in Rust and return the insertion index.',
    'My Dockerfile builds locally but fails in CI with a permission denied on the entrypoint — why?',
    'Write a TypeScript type that makes every property of an object optional except the id.',
    'How do I memoize an expensive selector in Redux Toolkit without stale results?',
    'Explain the difference between async/await and raw promises in JavaScript with an example.',
    'Optimize this nested loop that checks every pair of items; it is O(n^2) and too slow for 50k rows.',
    'Write a bash one-liner that finds all files over 100 MB modified in the last week.',
    'Why does this Go program deadlock when the channel is unbuffered?',
    'Migrate this Express middleware to Fastify and keep the same request logging.',
    'Create a SQL migration that adds a nullable column with a check constraint and backfills it.',
    'Write a Kubernetes readiness probe for a service that needs the database before it can serve.',
    'Implement an LRU cache class with O(1) get and put in Java.',
    'Debug why my CSS grid collapses to one column on Safari but not Chrome.',
    'Write a GitHub Actions workflow that runs tests on pull requests and caches node_modules.',
    'How do I handle a null pointer exception thrown from this Kotlin coroutine?',
    'Parse command-line flags in a C program using getopt and print usage on error.',
    "Explain the borrow checker error 'cannot move out of borrowed content' in this snippet.",
    'Write a recursive descent parser for arithmetic expressions with precedence.',
    'Set up ESLint and Prettier in a monorepo so both packages share one config.',
    'Why is my PostgreSQL index not used for this query with a LIKE prefix?',
    'Implement rate limiting with a token bucket in Python using asyncio.',
    'Write a unit test that mocks fetch and asserts the retry logic backs off exponentially.',
  ],
  research: [
    'Find and summarize the latest peer-reviewed studies on intermittent fasting and longevity.',
    'What is the current scientific consensus on the causes of the Bronze Age collapse?',
    'Compare the evidence for and against a four-day work week from published trials.',
    'Give me an overview of the state of solid-state battery research with citations.',
    'Investigate how different countries regulated ride-sharing and what outcomes were measured.',
    'Survey the main approaches to carbon capture and their reported costs per ton.',
    'What do meta-analyses say about the effectiveness of mindfulness apps for anxiety?',
    'Fact-check the claim that honey never spoils and cite the sources.',
    'Trace the history of the idea of universal basic income and its major pilot programs.',
    'Which economic studies measured the effect of minimum wage increases on employment, and what did they find?',
    "Summarize what is known about the microbiome's role in depression, separating established findings from hypotheses.",
    'Collect the key findings from reports on remote work productivity since 2020.',
    'What are the leading theories for why the Antikythera mechanism was built?',
    'Review the literature on spaced repetition and long-term retention in adult learners.',
    'What does the research say about screen time and sleep in adolescents?',
    'Gather the evidence on whether open-plan offices affect collaboration, with sources.',
    'Investigate the origins of the QWERTY layout and evaluate the competing explanations.',
    'What is known about the long-term effects of microplastics on human health so far?',
    'Compare how three major studies estimated the economic cost of air pollution.',
    'Summarize the history and current status of fusion energy projects worldwide.',
    'What did randomized trials find about cash transfers in low-income countries?',
    'Identify the main hypotheses about the Fermi paradox and who proposed them.',
    'Report on the state of research into psilocybin for treatment-resistant depression.',
    'What evidence exists on the effectiveness of speed cameras in reducing road deaths?',
    'Explain what historians currently believe about the causes of the Great Fire of London.',
    'Compile the reported outcomes of congestion pricing schemes in London, Stockholm, and Singapore.',
    'What does the literature say about bilingualism and the onset of dementia?',
    'Investigate whether the claims about cold-water immersion and recovery are supported by studies.',
    'Review the evidence on the health effects of artificial sweeteners from the last decade.',
    'What are the documented impacts of invasive lionfish on Caribbean reefs?',
  ],
  vision: [
    'What is in this picture?',
    'Read the text from this screenshot and tell me what the error says.',
    'Describe the chart in this image and the trend it shows.',
    'Does this photo of my plant show signs of overwatering?',
    'Identify the bird in this photo.',
    'Extract the table from this scanned receipt.',
    'Is the lesion in this photo something I should get checked?',
    'What breed is the dog in this picture?',
    'Transcribe the handwriting in this image.',
    'Which of these two photos is better composed and why?',
    'What landmark is shown in this photo?',
    'Count the people in this image.',
    'Tell me the ingredients listed on the label in this photo.',
    'What does this diagram of the circuit show?',
    'Translate the sign in this picture.',
    'Look at this floor plan and tell me where the bedrooms are.',
    'What is wrong with the posture in this photo of my desk setup?',
    'Describe the painting in this image and its style.',
    'Read the meter value from this photo.',
    'Is this mushroom in the picture edible?',
    'What kind of rash is shown in this image?',
    'Estimate the age of the tree in this photograph.',
    'Which wire is loose in this photo of the outlet?',
    'Summarize the slide shown in this screenshot.',
    'What car model is in this picture?',
    'Tell me what the graph in this image says about revenue by quarter.',
    'Find the typo on this screenshot of my website.',
    'What food is this in the photo and roughly how many calories?',
    'Describe the architecture style of the building in this picture.',
    'Read the license plate in this image.',
  ],
  structured: [
    'Return the following data as JSON with keys name, email, and signup_date.',
    'Extract every person, organization, and location from this text into a table.',
    'Give me a CSV of the ten largest countries by area with columns country and km2.',
    'Fill in this JSON schema with the values from the description.',
    'Parse this log line into fields: timestamp, level, service, message.',
    'Produce a YAML config for a web service with fields name, port, replicas, and env.',
    'List the meeting action items as a markdown table with columns owner, task, due date.',
    'Convert this bullet list of products into a JSON array of objects with price as a number.',
    'Output only a JSON object describing the sentiment and confidence of this review.',
    'Normalize these addresses into structured fields: street, city, postal code, country.',
    'Turn this recipe into a structured format with ingredients as a list and steps numbered.',
    'Give me the answer as an array of strings, no prose.',
    'Extract dates and amounts from this invoice into key-value pairs.',
    'Tabulate the pros and cons in two columns.',
    'Produce a JSON array of the top five tallest mountains with name, height_m, and range.',
    'Map these job titles to standardized categories and output a two-column table.',
    'Return the classification as one of the enum values: positive, negative, neutral.',
    "Create a TOML file for this project's settings with sections for build and deploy.",
    'Serialize this conversation into a list of objects with role and content.',
    'Break this paragraph into a structured outline with numbered headings and sub-points.',
    'Extract the product specs from this description into a spec sheet table.',
    'Give me a dictionary mapping each country to its capital for these ten countries.',
    'Output the schedule as an ICS-style list of events with start, end, and title.',
    'Convert this table in prose into a CSV with a header row.',
    'Summarize each support ticket in exactly three fields: issue, severity, next step.',
    'Return the parsed components of this URL as JSON: scheme, host, path, query parameters.',
    'Structure the medication list into name, dose, frequency, and route columns.',
    'Express this decision tree as nested JSON.',
    'Produce a markdown table comparing the three plans by price, seats, and storage.',
    'Return only valid JSON that lists the errors found, each with line and message.',
  ],
  writing: [
    'Write a cover letter for a junior data analyst position at a healthcare startup.',
    'Draft a polite email to my landlord asking to fix the heating before winter.',
    'Rewrite this paragraph to sound more confident without being arrogant.',
    'Compose a wedding toast for my sister that is warm and a little funny.',
    'Write a product description for a handmade ceramic mug.',
    'Draft a LinkedIn post announcing that I am starting a new role.',
    'Polish the abstract of my paper so it reads smoothly for a general audience.',
    'Write a 500-word blog post about why morning walks changed my routine.',
    'Turn these notes into a clear two-paragraph summary for the team.',
    'Write a short story about a lighthouse keeper who finds a message in a bottle.',
    'Make this apology email sincere but brief.',
    'Write the opening paragraph of a fantasy novel set in a desert city.',
    'Draft a thank-you note to a mentor who helped me through a hard year.',
    'Rewrite this job ad so it sounds welcoming and less corporate.',
    'Write a haiku sequence about autumn in the city.',
    'Help me word a message declining a meeting invitation gracefully.',
    'Compose a birthday card message for my grandfather turning ninety.',
    'Write an engaging introduction for a podcast episode about urban beekeeping.',
    'Tighten this essay to under 300 words while keeping the main argument.',
    'Write a persuasive paragraph arguing for more bike lanes downtown.',
    'Draft a speech for a retirement party for a colleague of twenty years.',
    "Write a children's bedtime story about a shy cloud.",
    "Rephrase this sentence so it is friendlier: 'Your request has been denied.'",
    'Write the about-us page for a small family bakery.',
    "Draft a newsletter intro for our community garden's spring update.",
    'Write a limerick about a cat who refuses to come inside.',
    'Edit this paragraph for flow and remove the passive voice.',
    'Write a heartfelt condolence message for a coworker who lost a parent.',
    'Create a catchy tagline and a short pitch for a reusable water bottle.',
    'Write a reflective journal entry about a long hike in the rain.',
  ],
};
